version: "3.9"
services:

  api:
   build: .
   ports:
     - 3000:3000
   container_name: mern-api
   restart: always
   depends_on:
    - db
    - cache

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    container_name: redis-cache
    command: [ "redis-server" ]

    volumes: 
      - redis-data:/data


volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local